# Generated by Django 4.2.7 on 2023-12-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crimes',
            fields=[
                ('dr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('date_occ', models.DateField(blank=True, null=True)),
                ('time_occ', models.TimeField(blank=True, null=True)),
                ('vict_age', models.IntegerField(blank=True, null=True)),
                ('vict_sex', models.CharField(blank=True, max_length=255, null=True)),
                ('vict_descent', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Crimes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crimetype',
            fields=[
                ('crime_code', models.IntegerField(primary_key=True, serialize=False)),
                ('crime_desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'CrimeType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premistype',
            fields=[
                ('premis_code', models.IntegerField(primary_key=True, serialize=False)),
                ('premis_desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'PremisType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('view_id', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Views',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weapontype',
            fields=[
                ('weapon_code', models.IntegerField(primary_key=True, serialize=False)),
                ('weapon_desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'WeaponType',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.CreateModel(
            name='Crimefilter',
            fields=[
                ('username', models.OneToOneField(db_column='Username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.users')),
            ],
            options={
                'db_table': 'CrimeFilter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Premisfilter',
            fields=[
                ('username', models.OneToOneField(db_column='Username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.users')),
            ],
            options={
                'db_table': 'PremisFilter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weaponfilter',
            fields=[
                ('username', models.OneToOneField(db_column='Username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.users')),
            ],
            options={
                'db_table': 'WeaponFilter',
                'managed': False,
            },
        ),
    ]
